# Generated by Django 5.2 on 2025-06-15 14:54

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='记录创建时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='记录最后修改时间', verbose_name='更新时间')),
                ('phone', models.CharField(help_text='用户注册和登录的手机号码', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码（11位数字，以1开头）', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, help_text='用户显示昵称', max_length=50, null=True, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, help_text='用户头像URL地址', null=True, verbose_name='头像')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记，不物理删除用户数据', verbose_name='是否删除')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'users_user',
                'indexes': [models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'), models.Index(fields=['is_active', 'is_deleted'], name='users_user_is_acti_748002_idx'), models.Index(fields=['add_time'], name='users_user_add_tim_27f1af_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
