# Generated by Django 5.2 on 2025-06-16 08:57

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', '-add_time'], name='idx_user_login_time'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['ip_address', '-add_time'], name='idx_ip_login_time'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['login_type', '-add_time'], name='idx_login_type_time'),
        ),
    ]
