# Generated by Django 5.2 on 2025-06-16 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loginlog_add_time_alter_user_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, help_text='用户的手机号，用于登录和验证', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号码格式', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
